### ISSUE TITLE
Git Repositories in Configuration Files

### ISSUE THREAD

**Issue by lenerd** [cryptobiu/MATRIX#12]
Hi,

in all of the example configuration files but `Config_ABY_InnerProduct.json`, the Git repository is given as a string, e.g.
https://github.com/cryptobiu/MATRIX/blob/77a331626027cc4c7c4855aff8fe640ecde15e69/ProtocolsConfigurations/Config_BMR.json#L7
However, a dictionary is expected, e.g.
https://github.com/cryptobiu/MATRIX/blob/77a331626027cc4c7c4855aff8fe640ecde15e69/ProtocolsConfigurations/Config_ABY_InnerProduct.json#L7-L9
Otherwise, the code breaks here
https://github.com/cryptobiu/MATRIX/blob/77a331626027cc4c7c4855aff8fe640ecde15e69/Execution/end_to_end.py#L24-L25

**Comment by liorbiu** [comment]
Hi,

Thank you for notice, I didn't upload some of the updated configuration files. I will upload them soon.

Lior
