### ISSUE TITLE
Install Experiment: Host not specified

### ISSUE THREAD

**Issue by lenerd** [cryptobiu/MATRIX#15]
Hi,
I have deployed instances (for the BMR protocol).
When I try to install the experiment, I get the following error from fabric:
```
 Fatal error: Needed to prompt for the target host connection string (host: None), but input would be ambiguous in parallel mode
```
This happenes here:
https://github.com/cryptobiu/MATRIX/blob/92cc27b504d4e7fa48dedfe0194e2633b375bc8e/Execution/end_to_end.py#L28-L29

If I drop the `--parallel` from the command line, I get asked to provide a host:
```
No hosts found. Please specify (single) host string for connection: 
```
Shouldn't this happen automatically?

**Comment by liorbiu** [comment]
#13
