### ISSUE TITLE
Why is working_directory a list?

### ISSUE THREAD

**Issue by GuutBoy** [cryptobiu/MATRIX#45]
In the MATRIX config, why is the `working_directory` a list? It always seems to be of length 1, so why not just a string?

**Comment by liorko87** [comment]
In most of the cases you are absolutely right.
There are cases that we needed to run different protocols with the same configuration one after the other.
Please take a look at the Comparison config file [here](https://github.com/cryptobiu/MATRIX/blob/master/ProtocolsConfigurations/Config_Comparison.json).

This is the reason that these paramters are list and not strings: 
- `workingDirectory`
- 'gitAddress`
- 'gitBranch'
- 'executableName'

**Comment by GuutBoy** [comment]
I see. You might want to document that.

**Comment by GuutBoy** [comment]
This seems to be causing problems when running pre process tasks, because `end_to_end.py` is treating it as a string rather than list.

**Comment by liorko87** [comment]
I'm working on full documentation of the system including detailed installation instructions and basic usage
