### ISSUE TITLE
Servers Deployment: Protocol gets executed locally instead

### ISSUE THREAD

**Issue by lenerd** [cryptobiu/MATRIX#51]
Hi,

I am trying to get MATRIX to work on a couple of (locally hosted) VMs (again). So, in the configuration I use "servers" in the "CloudProviders" section (see below for the full configuration file).

Hence, in `run_protocol` in `fabfile.py`, the variable `regions` is set to an empty list:

https://github.com/cryptobiu/MATRIX/blob/d27ef034cea26c2003908a2e65ef243abc7e790e/Execution/fabfile.py#L66-L73

As a consequence, MATRIX try to run the protocol on the local machine:

https://github.com/cryptobiu/MATRIX/blob/d27ef034cea26c2003908a2e65ef243abc7e790e/Execution/fabfile.py#L85-L95

So, the `servers` deployment need to be handled somewhat differently. Maybe, as another case in the first case distinction?

Or do I need to change something in the configuration?

---

```json
{
  "protocol": "ABY",
  "CloudProviders":
  {
    "servers":
    {
      "numOfParties": 2,
      "regions": ["servers"],
      "git":
      {
        "gitBranch": ["matrix"],
        "gitAddress": ["https://github.com/lenerd/ABY.git"]
      }
    }
  },
  "executableName": ["../src/examples/innerproduct/run_matrix.sh"],
  "configurations": ["-b@32"],
  "numOfRepetitions": 1,
  "numOfInternalRepetitions": 1,
  "IsPublished": "false",
  "isExternal": "true",
  "workingDirectory": ["~/ABY"],
  "resultsDirectory": "~/MATRIX/ExperimentReport/Results",
  "emails": ["lennart.braun@stud.tu-darmstadt.de"],
  "institute": "TU Darmstadt"
}
```

**Comment by liorko87** [comment]
Hi,

I add another option in the `fabfile.py` for local servers. Your configuration seems fine.
Please pull the latest commit.

Lior

**Comment by lenerd** [comment]
Thanks for fixing this! :)
